name: smart_kitchen_assistant
description: EcoBite smart kitchen assistant for reducing household food waste.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter_local_notifications: ^21.0.0
  flutter_timezone: ^5.0.2
  http: ^1.6.0
  intl: ^0.19.0
  mobile_scanner: ^7.2.0
  shared_preferences: ^2.5.5
  timezone: ^0.11.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/ecobite_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/ecobite_logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/ecobite_logo.png
